# recipes/recipe.yml

name: gnx
description: Universal Blue/Bazzite based image.
base-image: ghcr.io/ublue-os/bazzite
image-version: stable # ou 'latest'

# Aqui você escolhe a base exata.
# Para ter o PLASMA no Desktop e Deck:
base-image: ghcr.io/ublue-os/bazzite
# Se fosse só notebook GNOME, seria 'silverblue' ou 'bluefin'

modules:
  - type: files
    files:
      - usr: /usr # Copia arquivos customizados se você tiver

  - type: rpm-ostree
    repos:
      # Exemplo: Adicionar repo do VSCode ou Sublime se precisasse
      # - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      # --- Suas Ferramentas de Dev ---
      - git
      - code # VSCode
      - distrobox
      # - godot (Geralmente é melhor instalar via Flatpak, mas pode ser via RPM)

      # --- Ferramentas de Sistema ---
      - zsh
      - htop

  - type: default-flatpaks
    notify: true # Mostra notificação no primeiro boot
    system:
      # Instala automaticamente esses flatpaks
      - repo: flathub
        name: org.godotengine.Godot
      - repo: flathub
        name: org.blender.Blender

  - type: signing
    # Isso assina a imagem (importante para segurança)
