name: gnx
description: Minha imagem baseada no Bazzite
base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      # Repositorio do VSCode
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      # Ferramentas de Dev e Sistema
      - git
      - code
      - distrobox
      - zsh
      - htop
      # Adicione outros pacotes do sistema aqui se precisar

  - type: signing
