name: Build ISOs
on:
  workflow_dispatch: # Botão manual para você clicar

jobs:
  build-isos:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # --- ISO 1: WORKSTATION ---
      - name: Build Workstation ISO
        uses: blue-build/github-action@v1.8
        with:
          recipe: recipes/workstation.yml
          iso_name: gnx-workstation.iso

      - name: Upload Workstation ISO
        uses: actions/upload-artifact@v4
        with:
          name: gnx-workstation-iso
          path: ./output/gnx-workstation.iso
          if-no-files-found: warn

      # --- ISO 2: DECK ---
      - name: Build Deck ISO
        uses: blue-build/github-action@v1.8
        with:
          recipe: recipes/deck.yml
          iso_name: gnx-deck.iso

      - name: Upload Deck ISO
        uses: actions/upload-artifact@v4
        with:
          name: gnx-deck-iso
          path: ./output/gnx-deck.iso
          if-no-files-found: warn
