name: Build ISOs
on:
  workflow_dispatch: # Botão manual para você clicar

jobs:
  build-isos:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # --- ISO 1: WORKSTATION (AURORA) ---
      - name: Build Workstation ISO
        uses: blue-build/github-action@v1.11
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        with:
          recipe: recipes/workstation.yml
          iso_name: gnx-workstation.iso
          registry_token: ${{ github.token }}
          signing_secret: ${{ secrets.SIGNING_SECRET }} # <--- TEM QUE TER ISSO AQUI

      # --- ISO 2: DECK ---
      - name: Build Deck ISO
        uses: blue-build/github-action@v1.11
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        with:
          recipe: recipes/deck.yml
          iso_name: gnx-deck.iso
          registry_token: ${{ github.token }}
          signing_secret: ${{ secrets.SIGNING_SECRET }} # <--- E AQUI

      # --- ISO 3: WORKSTATION XE (BAZZITE) ---
      - name: Build Workstation XE ISO
        uses: blue-build/github-action@v1.11
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        with:
          recipe: recipes/workstation-xe.yml
          iso_name: gnx-workstation-xe.iso
          registry_token: ${{ github.token }}
          signing_secret: ${{ secrets.SIGNING_SECRET }} # <--- E AQUI TAMBÉM

      # --- ISO 4: SERVER (ALMALINUX BOOTC) ---
      - name: Build Server ISO
        uses: blue-build/github-action@v1.11
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        with:
          recipe: recipes/server.yml
          iso_name: gnx-server.iso
          registry_token: ${{ github.token }}
          signing_secret: ${{ secrets.SIGNING_SECRET }}
